version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: bookstore
      SQL_USER: bookstore_dev
      SQL_PASSWORD: 123456
      SQL_HOST: db
      SQL_PORT: 5432
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: